if(!window.fbq){!function(f,b,e,v,n,t,s){n=f.fbq=function(){n.callMethod?n.callMethod.apply(n,arguments):n.queue.push(arguments)};f._fbq=n;n.push=n;n.loaded=true;n.version='2.0';n.queue=[];t=b.createElement(e);t.async=true;t.src=v;s=b.getElementsByTagName(e)[0];s.parentNode.insertBefore(t,s)}(window,document,'script','https://connect.facebook.net/en_US/fbevents.js');fbq('init','1304248441807436');fbq('track','PageView')}
const BOOK='https://www.fresha.com/book-now/sterling-fade-co-ps8hgwns/services?lid=2894228&eid=5114480&share=true&pId=2798357';
document.querySelectorAll('[data-book]').forEach(a=>a.href=BOOK);
const menu=document.querySelector('.menu-btn'),links=document.querySelector('.nav-links');
if(menu){menu.addEventListener('click',()=>{const open=links.classList.toggle('open');menu.setAttribute('aria-expanded',open);document.body.classList.toggle('menu-open',open)});links.querySelectorAll('a').forEach(a=>a.addEventListener('click',()=>{links.classList.remove('open');document.body.classList.remove('menu-open')}))}
const observer=new IntersectionObserver(es=>es.forEach(e=>{if(e.isIntersecting){e.target.classList.add('visible');observer.unobserve(e.target)}}),{threshold:.12});document.querySelectorAll('.reveal').forEach(el=>observer.observe(el));
document.querySelectorAll('.faq-q').forEach(q=>q.addEventListener('click',()=>{const item=q.closest('.faq-item'),open=item.classList.toggle('open');q.setAttribute('aria-expanded',open)}));
const track=document.querySelector('.review-track');if(track){let i=0;const cards=[...track.children],move=d=>{i=(i+d+cards.length)%cards.length;track.style.transform=`translateX(-${i*100}%)`};document.querySelector('[data-prev]').onclick=()=>move(-1);document.querySelector('[data-next]').onclick=()=>move(1);setInterval(()=>move(1),6500)}
const progress=document.querySelector('.progress'),topBtn=document.querySelector('.back-top');window.addEventListener('scroll',()=>{const max=document.documentElement.scrollHeight-innerHeight;progress.style.width=(max?scrollY/max*100:0)+'%';topBtn.classList.toggle('show',scrollY>650)});topBtn?.addEventListener('click',()=>scrollTo({top:0,behavior:'smooth'}));
document.querySelectorAll('a[href*="fresha.com"]').forEach(a=>a.addEventListener('click',()=>{if(window.fbq)fbq('trackCustom','BookAppointmentClick')}));
